{{ if .Values.podScanner.enabled -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pod-scanner
  labels:
    app: pod-scanner
spec:
  selector:
    matchLabels:
      app: pod-scanner
  template:
    metadata:
      labels:
        app: pod-scanner
    spec:
      containers:
      - name: pod-scanner
        image: {{ .Values.podScanner.image.repository }}:{{ .Values.podScanner.image.tag }}
        imagePullPolicy: {{ .Values.podScanner.image.pullPolicy }}
#        resources:
#          requests:
#            memory: "2048Mi"
#            cpu: "1000m"
        env:
        - name: POTENTIAL_DOCKER_SOCKET_LOCATIONS
          value: {{ .Values.podScanner.scannerIntegration.potentialDockerSocketLocations }}
        - name: POTENTIAL_CONTAINERD_SNAPSHOT_LOCATIONS
          value: {{ .Values.podScanner.scannerIntegration.potentialContainerDSnapshotLocations }}
        - name: AWS_TAGS_PREFIX
          value: {{ .Values.podScanner.aws.tagPrefix }}
        - name: AWS_TAGS_INCLUDE_LIST
          value: {{ .Values.podScanner.aws.includeTagList }}
        - name: AWS_TAGS_EXCLUDE_LIST
          value: {{ .Values.podScanner.aws.exludeTagList }}
        - name: GCP_TAGS_PREFIX
          value: {{ .Values.podScanner.gcp.tagPrefix }}
        - name: GCP_TAGS_INCLUDE_LIST
          value: {{ .Values.podScanner.gcp.includeTagList }}
        - name: GCP_TAGS_EXCLUDE_LIST
          value: {{ .Values.podScanner.gcp.exludeTagList }}
        - name: K8S_VERIFY_SSL
          value: "{{ .Values.kubernetes.verifySSL }}"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName        
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP        
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: hostroot
          mountPath: /host
          readOnly: true
        - name: hostmounts
          mountPath: /hostmounts
          readOnly: true
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 2
          failureThreshold: 10
      volumes:
      - name: hostroot
        hostPath:
          path: /
          type: Directory
      - name: hostmounts
        hostPath:
          path: /proc/mounts
          type: File
{{end}}
