{
 "title": "Bjorn2Scan",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "staleness_window", "label": "Staleness window", "query": "6m,10m,16m,20m,30m,1h" },
   {
    "name": "deployment_name",
    "label": "Deployment",
    "query": {
     "query": "label_values(bjorn2scan_deployment,deployment_name)"
    }
   },
   {
    "name": "deployment_uuid",
    "label": "Deployment UUID",
    "query": {
     "query": "label_values(bjorn2scan_deployment{deployment_name=~\"$deployment_name\"},deployment_uuid)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(bjorn2scan_image_scanned{deployment_uuid=~\"$deployment_uuid\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Deployments",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (last_over_time(bjorn2scan_deployment{deployment_uuid=~\"$deployment_uuid\"}[$staleness_window]) >0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers Scanned",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (last_over_time(bjorn2scan_image_scanned{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (last_over_time(bjorn2scan_image_vulnerability{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Risk",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (last_over_time(bjorn2scan_image_vulnerability_risk{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exploits",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (last_over_time(bjorn2scan_image_vulnerability_exploited{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployment Overview",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(deployment_name, bjorn2scan_version, deployment_type, deployment_console, grype_db_built, deployment_uuid) (last_over_time(bjorn2scan_deployment{deployment_uuid=~\"$deployment_uuid\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(deployment_uuid) (last_over_time(bjorn2scan_image_scanned{deployment_uuid=~\"$deployment_uuid\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(deployment_uuid) (last_over_time(bjorn2scan_image_scan_status{deployment_uuid=~\"$deployment_uuid\", scan_status!=\"completed\"}[$staleness_window]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(deployment_uuid) (last_over_time(bjorn2scan_image_vulnerability{deployment_uuid=~\"$deployment_uuid\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(deployment_uuid) (last_over_time(bjorn2scan_image_vulnerability_risk{deployment_uuid=~\"$deployment_uuid\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(deployment_uuid) (last_over_time(bjorn2scan_image_vulnerability_exploited{deployment_uuid=~\"$deployment_uuid\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespace Summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (namespace)(last_over_time(bjorn2scan_image_scanned{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace)(last_over_time(bjorn2scan_image_vulnerability{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\", severity=\"Critical\"}[$staleness_window]) > 0) / sum by (namespace)(last_over_time(bjorn2scan_image_scanned{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace)(last_over_time(bjorn2scan_image_vulnerability{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\", severity=\"High\"}[$staleness_window]) > 0) / sum by (namespace)(last_over_time(bjorn2scan_image_scanned{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace)(last_over_time(bjorn2scan_image_vulnerability{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\", severity=\"Medium\"}[$staleness_window]) > 0) / sum by (namespace)(last_over_time(bjorn2scan_image_scanned{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace)(last_over_time(bjorn2scan_image_vulnerability{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\", severity=\"Low\"}[$staleness_window]) > 0) / sum by (namespace)(last_over_time(bjorn2scan_image_scanned{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace)(last_over_time(bjorn2scan_image_vulnerability{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\", severity=\"Negligible\"}[$staleness_window]) > 0) / sum by (namespace)(last_over_time(bjorn2scan_image_scanned{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace)(last_over_time(bjorn2scan_image_vulnerability{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\", severity=\"Unknown\"}[$staleness_window]) > 0) / sum by (namespace)(last_over_time(bjorn2scan_image_scanned{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace)(last_over_time(bjorn2scan_image_vulnerability_risk{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\"}[$staleness_window]) > 0) / sum by (namespace)(last_over_time(bjorn2scan_image_scanned{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace)(last_over_time(bjorn2scan_image_vulnerability_exploited{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\"}[$staleness_window]) > 0) / sum by (namespace)(last_over_time(bjorn2scan_image_scanned{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Image Summary",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by(image_reference, full_image_id, image_digest) (\n  label_join(\n    last_over_time(bjorn2scan_image_scanned{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\"}[$staleness_window]) > 0,\n    \"full_image_id\",\n    \".\",\n    \"image_reference\",\n    \"image_digest\"\n  )\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(full_image_id) (\n\tlabel_join(\n\t\tlast_over_time(bjorn2scan_image_vulnerability{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\", severity=\"Critical\"}[$staleness_window]) > 0,\n\t\t\"full_image_id\",\n\t\t\".\",\n\t\t\"image_reference\",\n\t\t\"image_digest\"\n\t)\n) / sum by(full_image_id) (\n\tlabel_join(\n\tlast_over_time(bjorn2scan_image_scanned{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\"}[$staleness_window]) > 0,\n\t\t\"full_image_id\",\n\t\t\".\",\n\t\t\"image_reference\",\n\t\t\"image_digest\"\n\t)\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(full_image_id) (\n\tlabel_join(\n\t\tlast_over_time(bjorn2scan_image_vulnerability{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\", severity=\"High\"}[$staleness_window]) > 0,\n\t\t\"full_image_id\",\n\t\t\".\",\n\t\t\"image_reference\",\n\t\t\"image_digest\"\n\t)\n) / sum by(full_image_id) (\n\tlabel_join(\n\tlast_over_time(bjorn2scan_image_scanned{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\"}[$staleness_window]) > 0,\n\t\t\"full_image_id\",\n\t\t\".\",\n\t\t\"image_reference\",\n\t\t\"image_digest\"\n\t)\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(full_image_id) (\n\tlabel_join(\n\t\tlast_over_time(bjorn2scan_image_vulnerability{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\", severity=\"Medium\"}[$staleness_window]) > 0,\n\t\t\"full_image_id\",\n\t\t\".\",\n\t\t\"image_reference\",\n\t\t\"image_digest\"\n\t)\n) / sum by(full_image_id) (\n\tlabel_join(\n\tlast_over_time(bjorn2scan_image_scanned{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\"}[$staleness_window]) > 0,\n\t\t\"full_image_id\",\n\t\t\".\",\n\t\t\"image_reference\",\n\t\t\"image_digest\"\n\t)\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(full_image_id) (\n\tlabel_join(\n\t\tlast_over_time(bjorn2scan_image_vulnerability{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\", severity=\"Low\"}[$staleness_window]) > 0,\n\t\t\"full_image_id\",\n\t\t\".\",\n\t\t\"image_reference\",\n\t\t\"image_digest\"\n\t)\n) / sum by(full_image_id) (\n\tlabel_join(\n\tlast_over_time(bjorn2scan_image_scanned{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\"}[$staleness_window]) > 0,\n\t\t\"full_image_id\",\n\t\t\".\",\n\t\t\"image_reference\",\n\t\t\"image_digest\"\n\t)\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(full_image_id) (\n\tlabel_join(\n\t\tlast_over_time(bjorn2scan_image_vulnerability{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\", severity=\"Negligible\"}[$staleness_window]) > 0,\n\t\t\"full_image_id\",\n\t\t\".\",\n\t\t\"image_reference\",\n\t\t\"image_digest\"\n\t)\n) / sum by(full_image_id) (\n\tlabel_join(\n\tlast_over_time(bjorn2scan_image_scanned{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\"}[$staleness_window]) > 0,\n\t\t\"full_image_id\",\n\t\t\".\",\n\t\t\"image_reference\",\n\t\t\"image_digest\"\n\t)\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(full_image_id) (\n\tlabel_join(\n\t\tlast_over_time(bjorn2scan_image_vulnerability{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\", severity=\"Unknown\"}[$staleness_window]) > 0,\n\t\t\"full_image_id\",\n\t\t\".\",\n\t\t\"image_reference\",\n\t\t\"image_digest\"\n\t)\n) / sum by(full_image_id) (\n\tlabel_join(\n\tlast_over_time(bjorn2scan_image_scanned{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\"}[$staleness_window]) > 0,\n\t\t\"full_image_id\",\n\t\t\".\",\n\t\t\"image_reference\",\n\t\t\"image_digest\"\n\t)\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(full_image_id) (\n\tlabel_join(\n\t\tlast_over_time(bjorn2scan_image_vulnerability_risk{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\"}[$staleness_window]) > 0,\n\t\t\"full_image_id\",\n\t\t\".\",\n\t\t\"image_reference\",\n\t\t\"image_digest\"\n\t)\n) / sum by(full_image_id) (\n\tlabel_join(\n\tlast_over_time(bjorn2scan_image_scanned{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\"}[$staleness_window]) > 0,\n\t\t\"full_image_id\",\n\t\t\".\",\n\t\t\"image_reference\",\n\t\t\"image_digest\"\n\t)\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(full_image_id) (\n\tlabel_join(\n\t\tlast_over_time(bjorn2scan_image_vulnerability_exploited{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\"}[$staleness_window]) > 0,\n\t\t\"full_image_id\",\n\t\t\".\",\n\t\t\"image_reference\",\n\t\t\"image_digest\"\n\t)\n) / sum by(full_image_id) (\n\tlabel_join(\n\tlast_over_time(bjorn2scan_image_scanned{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\"}[$staleness_window]) > 0,\n\t\t\"full_image_id\",\n\t\t\".\",\n\t\t\"image_reference\",\n\t\t\"image_digest\"\n\t)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by(deployment_name, namespace, pod, container, deployment_uuid_namespace_pod_container) (label_join(last_over_time(bjorn2scan_image_scanned{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\"}[$staleness_window]) > 0, \"deployment_uuid_namespace_pod_container\", \".\", \"deployment_uuid\", \"namespace\", \"pod\", \"container\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(deployment_uuid_namespace_pod_container) (label_join(last_over_time(bjorn2scan_image_vulnerability{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\", severity=\"Critical\"}[$staleness_window]) > 0, \"deployment_uuid_namespace_pod_container\", \".\", \"deployment_uuid\", \"namespace\", \"pod\", \"container\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(deployment_uuid_namespace_pod_container) (label_join(last_over_time(bjorn2scan_image_vulnerability{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\", severity=\"High\"}[$staleness_window]) > 0, \"deployment_uuid_namespace_pod_container\", \".\", \"deployment_uuid\", \"namespace\", \"pod\", \"container\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(deployment_uuid_namespace_pod_container) (label_join(last_over_time(bjorn2scan_image_vulnerability{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\", severity=\"Medium\"}[$staleness_window]) > 0, \"deployment_uuid_namespace_pod_container\", \".\", \"deployment_uuid\", \"namespace\", \"pod\", \"container\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(deployment_uuid_namespace_pod_container) (label_join(last_over_time(bjorn2scan_image_vulnerability{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\", severity=\"Low\"}[$staleness_window]) > 0, \"deployment_uuid_namespace_pod_container\", \".\", \"deployment_uuid\", \"namespace\", \"pod\", \"container\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(deployment_uuid_namespace_pod_container) (label_join(last_over_time(bjorn2scan_image_vulnerability{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\", severity=\"Negligible\"}[$staleness_window]) > 0, \"deployment_uuid_namespace_pod_container\", \".\", \"deployment_uuid\", \"namespace\", \"pod\", \"container\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(deployment_uuid_namespace_pod_container) (label_join(last_over_time(bjorn2scan_image_vulnerability{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\", severity=\"Unknown\"}[$staleness_window]) > 0, \"deployment_uuid_namespace_pod_container\", \".\", \"deployment_uuid\", \"namespace\", \"pod\", \"container\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(deployment_uuid_namespace_pod_container) (label_join(last_over_time(bjorn2scan_image_vulnerability_risk{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\"}[$staleness_window]) > 0, \"deployment_uuid_namespace_pod_container\", \".\", \"deployment_uuid\", \"namespace\", \"pod\", \"container\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(deployment_uuid_namespace_pod_container) (label_join(last_over_time(bjorn2scan_image_vulnerability_exploited{deployment_uuid=~\"$deployment_uuid\", namespace=~\"$namespace\"}[$staleness_window]) > 0, \"deployment_uuid_namespace_pod_container\", \".\", \"deployment_uuid\", \"namespace\", \"pod\", \"container\"))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}